Transform: AWS::Serverless-2016-10-31
Parameters:
  TableName:
    Type: String
    Default: stripe-event-log
    Description: (Required) Name of table on DynamoDB to write order information to.
    ConstraintDescription: Required to write to DynamoDB. Table must be created before.
  StripeWebhookSecret:
    Type: String
    Default: wshec_1234
    Description: (Required) Your Stripe webhooks secret
  StripeSecretKey:
    Type: String
    Default: sk_12345
    Description: (Required) Your Stripe secret key
Resources:
  EventReciever:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs8.10
      Handler: event-receiver.handler
      CodeUri: ./src
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
          STRIPE_WEBHOOK_SECRET: !Ref StripeWebhookSecret
          STRIPE_SECRET_KEY: !Ref StripeSecretKey
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: '*'
      # Event sources to attach to this function. In this case, we are attaching
      # one API Gateway endpoint to the Lambda function. The function is
      # called when a HTTP request is made to the API Gateway endpoint.
      Events:
        WebhookEndpoint:
            # Define an API Gateway endpoint that responds to HTTP GET at /thumbnail
            Type: Api
            Properties:
                Path: /webhook
                Method: POST
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      TableName: !Ref TableName
      
  EventProcessor:
    Type: AWS::Serverless::Function
    Properties:
      Policies: AWSLambdaDynamoDBExecutionRole
      Runtime: nodejs8.10
      Handler: event-processor.handler
      CodeUri: ./src
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt DynamoDBTable.StreamArn
            BatchSize: 100
            StartingPosition: TRIM_HORIZON
