Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  TableName:
    Type: String
    Default: 'TableName'
    Description: (Required) Name of table on DynamoDB to write order information to.
    ConstraintDescription: 'Required to write to DynamoDB. Table must be created before.'
  StripeWebhookSecret:
    Type: String
    Default: 'wshec_1234'
    Description: '(Required) Your Stripe webhooks secret'
Resources:
  UpdateDBFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: nodejs8.10
      Handler: index.handler
      CodeUri: ./src
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
          STRIPE_WEBHOOK_SECRET: !Ref StripeWebhookSecret
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:PutItem'
              Resource: '*'
      # Event sources to attach to this function. In this case, we are attaching
      # one API Gateway endpoint to the Lambda function. The function is
      # called when a HTTP request is made to the API Gateway endpoint.
      Events:
        WebhookHandler:
            # Define an API Gateway endpoint that responds to HTTP GET at /webhook
            Type: Api
            Properties:
                Path: /webhook
                Method: POST
